package svc

import (
	"github.com/DotNetAge/gort/pkg/gateway"
)

type RPCHandlerRegistry struct {
	daemon *Daemon
}

func NewRPCHandlerRegistry(d *Daemon) *RPCHandlerRegistry {
	return &RPCHandlerRegistry{daemon: d}
}

func (r *RPCHandlerRegistry) handlers() map[string]gateway.MethodHandler {
	return map[string]gateway.MethodHandler{
		"session.list":               r.daemon.handleSessionList,
		"session.get":                r.daemon.handleSessionGet,
		"session.meta":               r.daemon.handleSessionMeta,
		"session.create":             r.daemon.handleSessionCreate,
		"session.delete":             r.daemon.handleSessionDelete,
		"session.confirm_files":      r.daemon.handleSessionConfirmFiles,
		"session.rollback_files":     r.daemon.handleSessionRollbackFiles,
		"session.truncate":           r.daemon.handleSessionTruncate,
		"memory.query":               r.daemon.handleMemoryQuery,
		"memory.store":               r.daemon.handleMemoryStore,
		"memory.delete":              r.daemon.handleMemoryDelete,
		"memory.chunks":              r.daemon.handleMemoryChunks,
		"memory.get_chunks":          r.daemon.handleMemoryGetChunks,
		"memory.count":               r.daemon.handleMemoryCount,
		"agent.list":                 r.daemon.handleAgentList,
		"agent.get":                  r.daemon.handleAgentGet,
		"agent.create":               r.daemon.handleAgentCreate,
		"agent.update":               r.daemon.handleAgentUpdate,
		"agent.score":                r.daemon.handleAgentScore,
		"agent.reload":               r.daemon.handleAgentReload,
		"model.list":                 r.daemon.handleModelList,
		"model.get":                  r.daemon.handleModelGet,
		"model.switch":               r.daemon.handleModelSwitch,
		"model.create":               r.daemon.handleModelCreate,
		"model.update":               r.daemon.handleModelUpdate,
		"model.delete":               r.daemon.handleModelDelete,
		"provider.list":              r.daemon.handleProviderList,
		"provider.create":            r.daemon.handleProviderCreate,
		"provider.update":            r.daemon.handleProviderUpdate,
		"provider.delete":            r.daemon.handleProviderDelete,
		"skill.list":                 r.daemon.handleSkillList,
		"skill.get":                  r.daemon.handleSkillGet,
		"skill.reload":               r.daemon.handleSkillReload,
		"ask_user.reply":             r.daemon.handleAskUserReply,
		"permission.reply":           r.daemon.handlePermissionReply,
		"execution.resume":           r.daemon.handleExecutionResume,
		"message.cancel":             r.daemon.handleMessageCancel,
		"fs.list":                    r.daemon.handleFSList,
		"fs.read":                    r.daemon.handleFSRead,
		"fs.write":                   r.daemon.handleFSWrite,
		"fs.home":                    r.daemon.handleFSHome,
		"fs.mkdir":                   r.daemon.handleFSMkdir,
		"fs.rm":                      r.daemon.handleFSRm,
		"fs.mv":                      r.daemon.handleFSMv,
		"fs.reveal":                  r.daemon.handleFSReveal,
		"user.config":                r.daemon.handleUserConfig,
		"server.version":             r.daemon.handleServerVersion,
		"server.check_update":        r.daemon.handleServerCheckUpdate,
		"server.apply_update":        r.daemon.handleServerApplyUpdate,
		"server.restart_daemon":      r.daemon.handleServerRestartDaemon,
		"token.usage.overview":       r.daemon.handleTokenUsageOverview,
		"token.usage.monthly":        r.daemon.handleTokenUsageMonthly,
		"token.usage.by_model":       r.daemon.handleTokenUsageByModel,
		"token.usage.total":          r.daemon.handleTokenUsageTotal,
		"token.usage.session":        r.daemon.handleTokenUsageSession,
		"token.usage.session.detail": r.daemon.handleTokenUsageSessionDetail,
		"schedule.list":              r.daemon.handleScheduleList,
		"schedule.add":               r.daemon.handleScheduleAdd,
		"schedule.del":               r.daemon.handleScheduleDelete,
		"log.read":                   r.daemon.handleLogRead,
		"log.clear":                  r.daemon.handleLogClear,
		"log.count":                  r.daemon.handleLogCount,
		"i18n.get":                   r.daemon.handleI18nGet,
		"i18n.switch":                r.daemon.handleI18nSwitch,
		"i18n.list":                  r.daemon.handleI18nList,
		"graph.query":                r.daemon.handleGraphQuery,
		"graph.exec":                 r.daemon.handleGraphExec,
		"graph.upsert_nodes":         r.daemon.handleGraphUpsertNodes,
		"graph.upsert_edges":         r.daemon.handleGraphUpsertEdges,
		"graph.get_node":             r.daemon.handleGraphGetNode,
		"graph.get_neighbors":        r.daemon.handleGraphGetNeighbors,
		"graph.list_nodes":           r.daemon.handleGraphListNodes,
		"graph.list_edges":           r.daemon.handleGraphListEdges,
		"graph.list_nodes_by_region": r.daemon.handleGraphListNodesByProject,
		"kvstore.get":                r.daemon.handleKVGet,
		"kvstore.set":                r.daemon.handleKVSet,
		"kvstore.delete":             r.daemon.handleKVDelete,
		"kvstore.list":               r.daemon.handleKVList,
		"kvstore.batch_set":          r.daemon.handleKVBatchSet,
		"kvstore.clear":              r.daemon.handleKVClear,
		"rule.list":                  r.daemon.handleRuleList,
		"rule.get":                   r.daemon.handleRuleGet,
		"rule.create":                r.daemon.handleRuleCreate,
		"rule.update":                r.daemon.handleRuleUpdate,
		"rule.delete":                r.daemon.handleRuleDelete,
		"kb.search":                  r.daemon.handleKBSearch,
		"kb.count":                   r.daemon.handleKBCount,
		"kb.chunks":                  r.daemon.handleKBChunks,
		"kb.chunks.get":              r.daemon.handleKBChunksGet,
		"kb.stats":                   r.daemon.handleKBStats,
		"kb.index.list":              r.daemon.handleKBIndexList,
		"kb.index.add":               r.daemon.handleKBIndexAdd,
		"kb.index.remove":            r.daemon.handleKBIndexRemove,
		"kb.index.enqueue":           r.daemon.handleKBIndexEnqueue,
		"kb.schema_properties":       r.daemon.handleSchemaProperties,
		"kb.file_states":             r.daemon.handleKBFileStates,
		"kb.check_region_health":     r.daemon.handleKBCheckRegionHealth,
		"kb.repair_region":           r.daemon.handleKBRepairRegion,
		"entity_tags.get":            r.daemon.handleEntityTagsGet,
		"entity_tags.save":           r.daemon.handleEntityTagsSave,
		"schema.get":                 r.daemon.handleSchemaGet,
		"schema.save":                r.daemon.handleSchemaSave,
		"schema.list":                r.daemon.handleSchemaList,
		"terminal.start":             r.daemon.handleTerminalStart,
		"terminal.input":             r.daemon.handleTerminalInput,
		"terminal.resize":            r.daemon.handleTerminalResize,
		"terminal.kill":              r.daemon.handleTerminalKill,
		"terminal.list":              r.daemon.handleTerminalList,
		"translate.rpc":              r.daemon.handleTranslate,
		"optimize.rpc":               r.daemon.handleOptimize,
	}
}

func (r *RPCHandlerRegistry) RegisterAll(gw *gateway.Server) {
	for method, handler := range r.handlers() {
		gw.RegisterMethod(method, handler)
	}
}
