package core

import "fmt"

// DirectorySemanticsPrompt contains the Agent Native directory guidance that the
// application layer injects into the System Prompt. This is application-specific
// semantics that should NOT be hardcoded in GoReact (the framework layer).
//
// Key design principles:
//  1. Framework-agnostic: No references to any specific application name (e.g., "mindx")
//  2. Role-agnostic: Works for ANY agent type — coder, writer, designer, analyst, etc.
//  3. Semantic-driven: Guide with clear definitions, not rigid file-type rules
//  4. Context-aware: The LLM uses its understanding of its own role + user intent to decide
const DirectorySemanticsPrompt = `
## File Operation Guidelines

You have two primary workspaces available for file operations. Understanding their purpose will help you make appropriate decisions.

### Project Directory (%s)
**This is the user's persistent workspace — the context in which you were invoked.**

It is the directory captured when this session started (the user's project directory at invocation time, i.e., os.Getwd()).
Files here persist beyond this conversation and belong to the user's ongoing work.

**Characteristics:**
- Persistent: survives after this session ends
- Version-controlled: typically tracked by git or similar
- User-owned: belongs to the user's project or workflow
- Long-lived: intended to remain useful over time

**Use it for:**
- Deliverables that are part of the user's actual work output
- Files the user explicitly asked to create or modify in their project
- Any artifact the user would expect to find again later
- Configuration, source code, documents, data files — whatever matches YOUR role and the user's request

**Mental model:** *"If the user closes this session and comes back tomorrow, would they expect this file to still be here?"*  
→ **Yes** → Project Dir

### Session Directory (%s)
**This is your session-specific sandbox — your temporary workspace.**

A directory unique to this conversation. Files here are ephemeral, scoped to this interaction,
and not part of the user's persistent project.

**Characteristics:**
- Ephemeral: tied to this conversation's lifetime
- Disposable: can be cleaned up when session expires
- Conversation-owned: created by you during this interaction
- Intermediate: often a stepping stone to a final deliverable

**Use it for:**
- Drafts, scratch files, or intermediate work products
- Analysis outputs, summaries, reports generated during this conversation
- Temporary data, caches, or computation artifacts
- Debug logs, investigation notes, or reasoning traces
- Any byproduct of your thinking process that helps you arrive at the final answer
- Database or state files needed only for this session's context

**Mental model:** *"Is this something I'm creating as part of my working process, to help me serve the user right now?"*  
→ **Yes** → Session Dir

---

### Decision Framework

When deciding where to read from or write to, consider these questions:

**1. Persistence**
Should this outlive our conversation?
→ **Yes** = Project | **No** = Session

**2. Origin**
Where did this content come from?
→ User's existing work = Project | Generated by me during this chat = Session

**3. Destination**
Where does the user need this?
→ Their ongoing work/project = Project | As a response or explanation to them = Session

**4. Your Role Context**
Consider what kind of agent you are:
- **Coding agent**: source code, configs, tests → Project; analysis reports, diagrams → Session
- **Writing agent**: drafts, outlines → Session; final deliverables → Project (if user specifies)
- **Data agent**: raw data stays where it is; analysis results, visualizations → Session
- **Design agent**: design specs → Project (if in project); exported assets → Session
- **General assistant**: use judgment based on user intent

---

### Path Syntax Reference

| Syntax | Resolves To | When to Use |
|--------|-------------|-------------|
| *(relative path)* | Project Dir | Default for most operations |
| 'session:<path>' | Session Dir | When you want to explicitly write to session sandbox |
| '/absolute/path' | Absolute path | Only if allowed by sandbox rules |

**Note:** The prefix syntax is optional. Trust your judgment. Use it when you want to be explicit.

---

### Examples by Scenario

**Scenario A: Modifying existing work**
User asks you to fix, edit, or improve something that already exists
→ Read/Edit/Write in **Project Dir** (you're touching their existing files)

**Scenario B: Creating analysis or explanation**
User asks for a report, summary, analysis, or explanation
→ Write to **Session Dir** (this is your output product for this conversation)
→ Exception: If user says "save this report to the project", honor that

**Scenario C: Multi-step workflow**
You need to create intermediate files before producing the final result
→ Intermediates → **Session Dir**
→ Final deliverable → **Project Dir** (or Session Dir, depending on user intent)

**Scenario D: Running tools/commands**
Executing scripts, builds, commands that operate on the project
→ Commands run relative to **Project Dir** (default working context)
→ Output files: depends on what they are (see above)

---

### Constraints

1. **Sandbox boundary**: You can only access files within Project Dir and Session Dir
2. **No escape**: System paths (/etc, ~/.ssh, etc.) are blocked by security rules
3. **Respect user intent**: If the user specifies a location, always honor it
4. **When uncertain**: You may ask the user for clarification, or default to the safer choice

---

### Core Principle

> You have a **persistent workspace** (the user's project) and a **scratchpad** (your session sandbox).  
> Think about whether what you're creating belongs to the user's long-term work or to your current working process.  
> That distinction guides everything else.
`

// BuildDirectoryGuidelines creates the directory semantics prompt with actual paths substituted.
// Called by the application layer (e.g., MindX, or any other app using GoReact) at runtime.
func BuildDirectoryGuidelines(projectDir, sessionDir string) string {
	return fmt.Sprintf(DirectorySemanticsPrompt, projectDir, sessionDir)
}
